# Generated by Django 3.0.6 on 2020-05-29 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hindiname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'Category Table',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hindiname', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Item List',
                'db_table': 'Manage your data table',
            },
        ),
    ]
