# Generated by Django 3.0.6 on 2020-05-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20200529_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image_url',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Category'),
        ),
    ]
