# Generated by Django 3.0.6 on 2020-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20200530_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sub_items',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
