# Generated by Django 3.0.6 on 2020-05-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20200531_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image_url',
            field=models.ImageField(default='', upload_to='grokey_images'),
        ),
    ]
