# Generated by Django 3.0.6 on 2020-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_auto_20200618_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unit',
            field=models.CharField(max_length=150),
        ),
    ]
